dist: precise
sudo: false      # Use container-based infrastructure
language: python

git:
  depth: 4

env:
  - LUA_RUNTIME="luajit"
    LUA_VERSION="5.2"
  - LUA_RUNTIME="luajit"
    LUA_VERSION="5.3"

before_install:
  - pip install hererocks
  - hererocks lua_installations/$LUA_RUNTIME$LUA_VERSION/ --luarocks ^ --$LUA_RUNTIME $LUA_VERSION
  - export PATH=$PATH:$PWD/lua_installations/$LUA_RUNTIME$LUA_VERSION/bin

before_script:
  - luarocks install busted
  - busted --version

script:
  - busted --verbose --output=TAP

cache:
  directories:
  - $PWD/lua_installations

notifications:
  email:
    recipients:
      - hanathatsme@gmail.com
    on_failure: always
